### PR TITLE
Fix Bugs, Caused by Hello Respones Types #811

### LINKED ISSUE #811: Conflict with Spring Data Redis with spring boot 3.3
### Describe the bug

When I use Garnet to replace Redis
My app written in Java with Spring Boot 3.3 and Spring Data Redis

I tried to test on container side and
Redis CLI works well in PING command
also Application's Execution of Ping works well

but Spring Application Try to connect Garnet, Fail to connect

and I checked logs, and finally found, when using Hello, fault on 

### Steps to reproduce the bug

1. create app with some Spring boot app with using Spring Data Redis, will trying to connect garnet
2. run garnet on docker container and run spring app
3. look fail message from spring boot's failure to application run

### Expected behavior

working well

### Screenshots

no prepared

### Release version

v1.0.36

### IDE

_No response_

### OS version

Ubuntu 24.04 LTS Host
running on docker compose (garnet latest, eclipse-temurin:21-jre

### Additional context

we operate garnet with out username and password, cause in docker network will ensure prevent to connect from external's

[failed codes](https://github.com/Prompt-oven/auth-service/blob/c87e39e7f93da52114dbb9f32d4c1d58db62deca/src/main/java/com/promptoven/authservice/adaptor/infrastructure/redis/RedisConfig.java)

[successed code](https://github.com/Prompt-oven/auth-service/blob/main/src/main/java/com/promptoven/authservice/adaptor/infrastructure/redis/RedisConfig.java)

### PR DESCRIPTION
**Pull request by yuseok-kim-edushare**
This PR will Fix Hello Responss's Type
To resolve #811 

### What is changed?
RESP hello command processing logic updated
to be same response as Redis's

https://github.com/redis/redis/blob/unstable/src/commands/hello.json

---
Thanks to @mp911de
He provide what is matter need to fix

And Also Thanks to @badrishc
He Support to me and provide tip to get trace log from garnet server

### CODE REVIEW

**Comment by yuseok-kim-edushare** [comment]
@microsoft-github-policy-service agree

**Comment by badrishc** [comment]
Excellent detective work! Really glad to see this get fixed :).

**Review by badrishc — APPROVED** [review]

File: libs/server/Resp/BasicCommands.cs [hunk 1]
```diff
@@ -1463,13 +1463,13 @@ void ProcessHelloCommand(byte? respProtocolVersion, ReadOnlySpan<byte> username,
...
-            (string, string)[] helloResult =
+            (string, object)[] helloResult =
                 [
                     ("server", "redis"),
                     ("version", storeWrapper.redisProtocolVersion),
                     ("garnet_version", storeWrapper.version),
-                    ("proto", $"{this.respProtocolVersion}"),
-                    ("id", "63"),
+                    ("proto", this.respProtocolVersion),
+                    ("id", 63),
```
Comment (badrishc) [inline libs/server/Resp/BasicCommands.cs:1472]: Please fix `AsyncTest1` in `RespTests.cs` -- set `expectedNewlineCount = 30` since there are two fewer newlines in the output.

Comment (yuseok-kim-edushare) [reply libs/server/Resp/BasicCommands.cs:1472]: Thanks! I'll try it!

**Review by badrishc — APPROVED** [review]
