### PR TITLE
Handling empty response TryReadStringArrayWithLengthHeader

### LINKED ISSUE #1008: GarnetClient threw 'System.IndexOutOfRangeException' when queried for CLUSTER SLOTS and no slots are assigned
### Describe the bug

```
var clusterSlotsResponse = await ExecuteCommandAsync("CLUSTER", "SLOTS").ConfigureAwait(false);
.
.
.
public async Task<string> ExecuteCommandAsync(string command, params string[] args)
{
    return await this.garnetClient.ExecuteForStringResultAsync(command, args).ConfigureAwait(false);
}
```

This throws exception when no slots are assigned. 

### Steps to reproduce the bug

Execute CLUSTER SLOTS using ExecuteCommandAsync when no slots are assigned to a given node.

### Expected behavior

_No response_

### Screenshots

_No response_

### Release version

_No response_

### IDE

_No response_

### OS version

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Xizt**
fixes #1008

### CODE REVIEW

File: libs/client/GarnetClientProcessReplies.cs [hunk 1]
```diff
@@ -54,7 +54,7 @@ unsafe bool ProcessReplyAsString(ref byte* ptr, byte* end, out string result, ou
                     if (!RespReadResponseUtils.TryReadStringArrayWithLengthHeader(out var resultArray, ref ptr, end))
                         return false;
                     // Return first element of array
-                    if (resultArray != null) result = resultArray[0];
+                    if (resultArray != null && resultArray.Length > 0) result = resultArray[0];
```
Comment (vazois) [inline libs/client/GarnetClientProcessReplies.cs:57]: Please add a test for this

**Review by vazois — CHANGES_REQUESTED** [review]

File: libs/client/GarnetClientProcessReplies.cs (hunk 1 above)
Comment (Xizt) [reply libs/client/GarnetClientProcessReplies.cs:57]: @vazois  Added. Please review if there needs to be changes.

File: test/Garnet.test/GarnetClientTests.cs [hunk 2]
```diff
@@ -354,6 +354,22 @@ public async Task CanUseSetNxStringResultAsync()
             ClassicAssert.AreEqual("Hello", resultMykey);
         }
 
+        [Test]
+        public async Task ShouldNotThrowExceptionForEmptyArrayResponse()
```
Comment (vazois) [inline test/Garnet.test/GarnetClientTests.cs:358]: Can you resolve the warning here?

**Review by vazois — CHANGES_REQUESTED** [review]

File: test/Garnet.test/GarnetClientTests.cs (hunk 2 above)
Comment (Xizt) [reply test/Garnet.test/GarnetClientTests.cs]: Kept the async pattern to match pattern in rest of the tests. Used async connection.

**Review by vazois — APPROVED** [review]
